"""Add User table

Revision ID: de202ef58179
Revises: c0bcf4568653
Create Date: 2025-01-25 23:27:44.858157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de202ef58179'
down_revision: Union[str, None] = 'c0bcf4568653'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('firstname', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('lastname', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('slug', sa.String(), nullable=True))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_slug'), 'users', ['slug'], unique=True)
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_slug'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'username',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('users', 'slug')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'age')
    op.drop_column('users', 'lastname')
    op.drop_column('users', 'firstname')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
